In [6]:
import numpy as np
N = np.random.random((5,5))
print('matrix\n',N)
N = (N - np.mean (N)) / (np.std (N))
print('normal matrix\n',N)

matrix
 [[0.33156499 0.52821652 0.02292824 0.85420596 0.24514862]
 [0.94454751 0.30617645 0.72998839 0.07635841 0.06498465]
 [0.14903656 0.13705737 0.44044006 0.3505205  0.72123067]
 [0.55846918 0.36647321 0.32426582 0.83556492 0.82112176]
 [0.22372274 0.02871222 0.72077756 0.78136245 0.00483464]]
normal matrix
 [[-0.30559927  0.35376358 -1.34044301  1.44679005 -0.59534906]
 [ 1.74970079 -0.39072579  1.03029469 -1.16129427 -1.19942994]
 [-0.91760803 -0.95777368  0.05945346 -0.24204237  1.00093048]
 [ 0.45519925 -0.18855374 -0.33007303  1.38428754  1.33586034]
 [-0.66718898 -1.3210496   0.9994112   1.20254933 -1.40110995]]
