In [1]:
import numpy as np
arr=np.random.random((3,3,3,))
print(arr)

[[[0.82115358 0.66914132 0.89990751]
  [0.92420511 0.21130661 0.92661704]
  [0.68213223 0.10644139 0.2337088 ]]

 [[0.27369664 0.39102687 0.37410105]
  [0.5680039  0.4919804  0.82380736]
  [0.06084625 0.78092576 0.44603815]]

 [[0.45067715 0.1048156  0.26980784]
  [0.43085051 0.11573517 0.45868994]
  [0.24687364 0.06068464 0.23842608]]]
